name: Coding Guidelines

on:
  pull_request:
  push:
    paths:
      - '.github/workflows/**'
      - 'phpunit.xml'
      - 'composer.json'
      - 'composer.lock'
      - '.prettierrc'
      - '.prettierignore'
      - '**.php'
      - '**.js'
      - '**.scss'
      - '**.json'
      - '**.md'
      - '**.yaml'
      - '**.yml'

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP 🔧
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none
          tools: composer:v2
        env:
          COMPOSER_TOKEN: ${{ secrets.TOKEN }}

      - name: Install Dependencies 🔧
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Run Pint
        run: vendor/bin/pint

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          package-manager-cache: false

      - name: Install Dependencies 🔧
        run: npm install --no-package-lock

      - name: Run Prettier
        run: npx prettier . --write

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Fixed code style
