name: Semgrep

on:
  pull_request:
  push:
    paths:
      - '.github/workflows/**'
      - '**.php'
      - '**.js'
      - '**.json'

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Run Semgrep 🔍
        run: semgrep scan --config auto --error
